.TH RT61-FWCUTTER "1" "DECEMBER 2006" "rt61-fwcutter" "User Commands"
.SH NAME
rt61-fwcutter \- extract firmware from Ralink rt61 drivers
.SH SYNOPSIS
.B rt61-fwcutter
[\fIOPTION\fR] [\fIDRIVER\fR]
.SH DESCRIPTION
rt61-fwcutter can extract the firmware for your Ralink rt61 hardware from different closed source drivers. The rt61 driver depends on this firmware files and can't work without them.
.PP
Example:
.IP
rt61-fwcutter RT61_Linux_STA_Drv1.1.0.0.tar.gz
.PP
to cut the firmware out of RT61_Linux_STA_Drv1.1.0.0.tar.gz
.SH AUTHORS
Stefan Lippers-Hollmann <s.l-h@gmx.de>, modelled after bcm43xx-fwcutter
